### ISSUE TITLE
Functional patterns and functional js workshop

### ISSUE THREAD

**Issue by zOadT** [jkup/functional-javascript#2]
Here are my 2 cents:

A video about functional programming patterns:
https://www.youtube.com/watch?v=AvgwKjTPMmM

Slides about functional programming in JavaScript:
https://github.com/fuzzyalej/intro-functional-js-workshop

Also kind of interesting, an article about generating HTML markup with functional programming:
https://bjpelc.wordpress.com/2015/02/13/generate-html-markup-in-javascript-with-pure-functional-programming/

**Comment by jkup** [comment]
Thanks! I'll add these in later today

**Comment by jkup** [comment]
I think I'm just going to add the first link for now. I'm not sure how best to handle slideshows at this time. Thanks for submitting!
